import { ShopItem } from '../types';
import { GAME_ASSETS } from './gameAssets';

const RIM_NET = GAME_ASSETS.hoop.rimNetClassic;

export const SHOP_CATALOG: ShopItem[] = [
  // —— Balls (galaxy = most expensive) ——
  {
    id: 'ball-classic',
    category: 'balls',
    name: 'Classic Orange',
    cost: 0,
    color: '#FF6B35',
    defaultUnlocked: true,
    imageSource: GAME_ASSETS.ball.classic,
  },
  {
    id: 'ball-ice',
    category: 'balls',
    name: 'Blizzard Ice',
    cost: 75,
    color: '#4FC3F7',
    imageSource: GAME_ASSETS.ball.ice,
  },
  {
    id: 'ball-candy',
    category: 'balls',
    name: 'Candy Swirl',
    cost: 150,
    color: '#F48FB1',
    imageSource: GAME_ASSETS.ball.candy,
  },
  {
    id: 'ball-fire',
    category: 'balls',
    name: 'Flame Ball',
    cost: 275,
    color: '#EF5350',
    imageSource: GAME_ASSETS.ball.fire,
  },
  {
    id: 'ball-gold',
    category: 'balls',
    name: 'Golden Legend',
    cost: 500,
    color: '#FFD54F',
    imageSource: GAME_ASSETS.ball.gold,
  },
  {
    id: 'ball-galaxy',
    category: 'balls',
    name: 'Galaxy Cosmic',
    cost: 950,
    color: '#7E57C2',
    imageSource: GAME_ASSETS.ball.galaxy,
  },

  // —— Backboards: basic = template color swaps ——
  {
    id: 'backboard-standard',
    category: 'backboards',
    name: 'Classic Orange',
    cost: 0,
    color: '#FF9800',
    defaultUnlocked: true,
    backboardImage: GAME_ASSETS.hoop.backboardClassic,
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-crimson',
    category: 'backboards',
    name: 'Crimson',
    cost: 45,
    color: '#E53935',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-neon',
    category: 'backboards',
    name: 'Neon Green',
    cost: 65,
    color: '#69F0AE',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-ocean',
    category: 'backboards',
    name: 'Ocean Blue',
    cost: 65,
    color: '#29B6F6',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-carbon',
    category: 'backboards',
    name: 'Carbon Steel',
    cost: 85,
    color: '#78909C',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-purple',
    category: 'backboards',
    name: 'Purple Glass',
    cost: 95,
    color: '#AB47BC',
    rimNetImage: RIM_NET,
  },

  // —— Backboards: premium = template + visual FX ——
  {
    id: 'backboard-stars',
    category: 'backboards',
    name: 'Starry Night',
    cost: 320,
    color: '#283593',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-blizzard',
    category: 'backboards',
    name: 'Blizzard Frost',
    cost: 380,
    color: '#B3E5FC',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-fire',
    category: 'backboards',
    name: 'Inferno',
    cost: 420,
    color: '#E65100',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-cracks',
    category: 'backboards',
    name: 'Shattered',
    cost: 460,
    color: '#424242',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-bones',
    category: 'backboards',
    name: 'Bone Yard',
    cost: 520,
    color: '#5D4037',
    rimNetImage: RIM_NET,
  },
  {
    id: 'backboard-clouds',
    category: 'backboards',
    name: 'Sky Clouds',
    cost: 580,
    color: '#4FC3F7',
    rimNetImage: RIM_NET,
  },

  // —— Backgrounds: cheap color/procedural first, then image courts (cost ∝ visual complexity) ——
  {
    id: 'bg-court-green',
    category: 'backgrounds',
    name: 'Sunny Backyard',
    cost: 0,
    color: '#B8E6F5',
    secondaryColor: '#7EC8E3',
    defaultUnlocked: true,
  },
  {
    id: 'bg-sunset',
    category: 'backgrounds',
    name: 'Sunset Backyard',
    cost: 45,
    color: '#FFCC80',
    secondaryColor: '#FF8A65',
  },
  {
    id: 'bg-night',
    category: 'backgrounds',
    name: 'Twilight Yard',
    cost: 70,
    color: '#5C6BC0',
    secondaryColor: '#3949AB',
  },
  {
    id: 'bg-arena',
    category: 'backgrounds',
    name: 'Autumn Yard',
    cost: 100,
    color: '#FFE082',
    secondaryColor: '#FFB74D',
  },
  {
    id: 'bg-city',
    category: 'backgrounds',
    name: 'Urban Skyline',
    cost: 350,
    color: '#64B5F6',
    secondaryColor: '#42A5F5',
    imageSource: GAME_ASSETS.background.city,
  },
  {
    id: 'bg-tropical-sunset',
    category: 'backgrounds',
    name: 'Tropical Sunset',
    cost: 430,
    color: '#FFAB91',
    secondaryColor: '#FF7043',
    imageSource: GAME_ASSETS.background.sunset,
  },
  {
    id: 'bg-bones',
    category: 'backgrounds',
    name: 'Bone Wasteland',
    cost: 510,
    color: '#D7CCC8',
    secondaryColor: '#A1887F',
    imageSource: GAME_ASSETS.background.bones,
  },
  {
    id: 'bg-snow',
    category: 'backgrounds',
    name: 'Winter Frost',
    cost: 590,
    color: '#B3E5FC',
    secondaryColor: '#81D4FA',
    imageSource: GAME_ASSETS.background.snow,
  },
  {
    id: 'bg-sky',
    category: 'backgrounds',
    name: 'Cloud Kingdom',
    cost: 670,
    color: '#81D4FA',
    secondaryColor: '#4FC3F7',
    imageSource: GAME_ASSETS.background.sky,
  },
  {
    id: 'bg-ocean',
    category: 'backgrounds',
    name: 'Deep Ocean',
    cost: 750,
    color: '#26C6DA',
    secondaryColor: '#00838F',
    imageSource: GAME_ASSETS.background.ocean,
  },
  {
    id: 'bg-jungle',
    category: 'backgrounds',
    name: 'Jungle Court',
    cost: 830,
    color: '#66BB6A',
    secondaryColor: '#2E7D32',
    imageSource: GAME_ASSETS.background.jungle,
  },
  {
    id: 'bg-starry-court',
    category: 'backgrounds',
    name: 'Starry Night Court',
    cost: 910,
    color: '#5C6BC0',
    secondaryColor: '#283593',
    imageSource: GAME_ASSETS.background.starryCourt,
  },
  {
    id: 'bg-volcano',
    category: 'backgrounds',
    name: 'Volcano Inferno',
    cost: 1030,
    color: '#FF7043',
    secondaryColor: '#BF360C',
    imageSource: GAME_ASSETS.background.volcano,
  },
  {
    id: 'bg-space',
    category: 'backgrounds',
    name: 'Galaxy Cosmos',
    cost: 1150,
    color: '#7E57C2',
    secondaryColor: '#4527A0',
    imageSource: GAME_ASSETS.background.space,
  },
];

export function getShopItem(id: string): ShopItem | undefined {
  return SHOP_CATALOG.find((item) => item.id === id);
}

export function getItemsByCategory(category: ShopItem['category']): ShopItem[] {
  return SHOP_CATALOG.filter((item) => item.category === category);
}
